### ISSUE TITLE
Cannot install the collection ibm.storage_virtualize

### ISSUE THREAD

**Issue by MMarceLL123** [ansible-collections/ibm.storage_virtualize#13]
Cannot install the collection.

ansible-galaxy installation command:
`ansible-galaxy collection install ibm.storage_virtualize`

> Starting galaxy collection install process
> Process install dependency map
> ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
> bm.storage_virtualize:* (direct request)

more details:
`ansible-galaxy collection install ibm.storage_virtualize -vvvv`

> ansible-galaxy [core 2.15.2]
>   config file = /home/xxx/ansible/ansible.cfg
>   configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python3/dist-packages/ansible
>   ansible collection location = /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections
>   executable location = /usr/bin/ansible-galaxy
>   python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
>   jinja version = 3.0.3
>   libyaml = True
> Using /home/xxx/ansible/ansible.cfg as config file
> Starting galaxy collection install process
> Loading collection dellemc.openmanage from /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/dellemc/openmanage
> Found installed collection dellemc.openmanage:8.0.0 at '/home/xx/ansible/home/xxx/.ansible/collections/ansible_collections/dellemc/openmanage'
> Loading collection ibm.spectrum_virtualize from /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/ibm/spectrum_virtualize
> Found installed collection ibm.spectrum_virtualize:2.0.0 at '/home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/ibm/spectrum_virtualize'
> Loading collection ansible.utils from /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/ansible/utils
> Found installed collection ansible.utils:2.10.3 at '/home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/ansible/utils'
> Loading collection community.general from /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/community/general
> Found installed collection community.general:7.3.0 at '/home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/community/general'
> Loading collection ansible.windows from /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/ansible/windows
> Found installed collection ansible.windows:2.0.0 at '/home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/ansible/windows'
> Loading collection brocade.fos from /home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/brocade/fos
> Found installed collection brocade.fos:1.3.3 at '/home/xxx/ansible/home/xxx/.ansible/collections/ansible_collections/brocade/fos'
> Process install dependency map
> Initial connection to galaxy_server: https://galaxy.ansible.com
> Opened /home/xxx/.ansible/galaxy_token
> Calling Galaxy at https://galaxy.ansible.com/api/
> Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
> Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/ibm/storage_virtualize/
> ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
> ibm.storage_virtualize:* (direct request)

The calling request to https://galaxy.ansible.com/api/v2/collections/ibm/storage_virtualize/

> HTTP 404 Not Found
>   Allow: GET, HEAD, OPTIONS
>   Content-Type: application/json
>   Vary: Accept
>   {
>     "code": "not_found",
>     "message": "Not found."
> }

Best regards

**Comment by MMarceLL123** [comment]
@Shilpi-J : Hello... yes, the installation is now possible without errors. But the documentation in Galaxy-Websites still refer to the old ibm.spectrum_virtualize plugin: https://docs.ansible.com/ansible/latest/collections/ibm/spectrum_virtualize/index.html

**Comment by Shilpi-J** [comment]
sure @MMarceLL123 We are working on it and will be done soon.
Thanks
