### ISSUE TITLE
Password policy for ibm_svc_manage_user

### ISSUE THREAD

**Issue by jishnujittm** [ansible-collections/ibm.storage_virtualize#20]
##### SUMMARY
Hello team,
I'd like to check for the possibility of adding a password policy with brocade_security_user_config.
Currently the module accepts any plain text as password.

Is it possible to have some checks here to notify the user that the password should meet certain criteria (for e.g. Minimum length, usage of special characters etc.)?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ibm_svc_manage_user

**Comment by sumitguptaibm** [comment]
@jishnujittm , This has been addressed via ibm_sv_manage_security module. Password rules can now be set via playbook. 
Documentation: #https://docs.ansible.com/ansible/latest/collections/ibm/storage_virtualize/ibm_sv_manage_security_module.html#ansible-collections-ibm-storage-virtualize-ibm-sv-manage-security-module

I hope this resolves your query. Please let us know if this issue can be closed. In case of no response, the issue will be closed by 3rd January, 2024.
