### ISSUE TITLE
FS9K initial setup - Support needed for creating  password policy and setting up Syslog

### ISSUE THREAD

**Issue by vishnupr-1** [ansible-collections/ibm.storage_virtualize#23]
##### SUMMARY
As a part of doing the initial setup of FS9K, it is required to execute the commands "chsecurity" and "mksyslogserver" for creating  password policy and setting up Syslog for LogDNA and Radar. But no modules are available for that.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Create password policy (for fs9k higher than v8.4.x)
Setup LogDNA and Qradar

##### ADDITIONAL INFORMATION
for password policy:

```
chsecurity -guitimeout -clitimeout -minpasswordlength -passwordspecialchars -passworduppercase 
-passwordlowercase -passworddigits -checkpasswordhistory -maxpasswordhistory  -minpasswordage
-passwordexpiry -maxfailedlogins -lockoutperiod
```
for syslog:

```
mksyslogserver -ip  -login  -audit -cadf -error -warning -info -protocol -port


```

**Comment by Shilpi-J** [comment]
Both features have been implemented in new version of collection v 2.1.0
Feel free to reach out to us in case you face any issue while using new modules.
