### ISSUE TITLE
Please add a modul to configure proxy settings

### ISSUE THREAD

**Issue by MMarceLL123** [ansible-collections/ibm.storage_virtualize#28]
Hello,

please can you add a seperate module to configure the proxy settings?

The modul ibm_svc_manage_callhome includes setting up the proxy settings, but you always have to specify all call home data.
This is difficult with systems that are in different locations.

##### ISSUE TYPE
- Feature Idea

Thnks for your response.

**Comment by sumitguptaibm** [comment]
@MMarceLL123 , I am not sure I understand "all call home data" in your question. Can you please elaborate with an example?

**Comment by sumitguptaibm** [comment]
@MMarceLL123 ,
We'll look into this. It seems like few parameters can be made optional in same module for this.
