### ISSUE TITLE
censorcallhome: on does not affect

### ISSUE THREAD

**Issue by MMarceLL123** [ansible-collections/ibm.storage_virtualize#33]
##### SUMMARY
Using 'ibm_svc_manage_callhome' does not affect 'censorcallhome: on' on IBM FlashSystems Firmware 8.6.0.1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm_svc_manage_callhome

##### ANSIBLE VERSION
ansible [core 2.15.6]
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

##### COLLECTION VERSION
ibm.storage_virtualize        2.1.0  

##### STEPS TO REPRODUCE
play:
  - name: Configure callhome & PROXY
    ibm.storage_virtualize.ibm_svc_manage_callhome:
      clustername: "{{ ansible_host }}"
      username: "xxx"
      password: "xxx"
      token: "xxx"
      state: "enabled"
      callhome_type: "both"
      proxy_type: "open_proxy"
      proxy_url: "http://xxx.com"
      proxy_port: 8xxx
      serverIP:  "smtp.xxx.com"
      serverPort: 25
      inventory: "on"
      invemailinterval: 8
      enhancedcallhome: "on"
      censorcallhome: "on"
      company_name: "{{callhome_daten.email_organization}}"
      address: "{{callhome_daten.email_machine_address}}"
      city: "{{callhome_daten.email_machine_city}}"
      province: "{{callhome_daten.email_machine_state}}"
      postalcode: "{{callhome_daten.email_machine_zip}}"
      country: "{{callhome_daten.email_machine_country}}"
      location: "{{callhome_daten.email_contact_location}}"
      contact_name: "{{callhome_daten.email_contact}}"
      contact_email: "{{callhome_daten.email_reply}}"
      phonenumber_primary: "{{callhome_daten.email_contact_primary}}"
    when: info_storage.System.code_level[0:3] | float >= 8.5
    register: output_callhome
```

**Comment by sumitguptaibm** [comment]
@MMarceLL123 , thanks for contacting us. This will be fixed in upcoming release.

**Comment by sumitguptaibm** [comment]
This issue has been fixed in latest release (2.4.1), thus closing the defect. Please install the latest collection to get the fix.
