### ISSUE TITLE
The collection contains an unmodified docs/docsite/links.yml file

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/ibm.storage_virtualize#41]
##### SUMMARY
The collection contains an unmodified docs/docsite/links.yml file (https://github.com/ansible-collections/ibm.storage_virtualize/blob/develop/docs/docsite/links.yml) from the collection template.

Please either delete that file, or actually fill it out with correct values!

The result of this file unchanged is:
- The "Report an issue" in the collection and all module/plugin docs button leads to a broken link: https://docs.ansible.com/ansible/devel/collections/ibm/storage_virtualize/ibm_sv_manage_awss3_cloudaccount_module.html#collection-links
- If you click on "Edit on GitHub" at the top-right of https://docs.ansible.com/ansible/devel/collections/ibm/storage_virtualize/ibm_sv_manage_awss3_cloudaccount_module.html and any other module/plugin docs, the link is also broken

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docs/docsite/links.yml

**Comment by felixfontein** [comment]
@sumitguptaibm you were listed as a maintainer for this collection when applying for inclusion in the Ansible community package. Can you please take a look at this soon? Thanks.

**Comment by sumitguptaibm** [comment]
@felixfontein , sure !! I'll try to get some time possibly in next week to fill correct info and close this.

**Comment by felixfontein** [comment]
Please also note that you currently have two of the CI pipelines disabled (https://github.com/ansible-collections/ibm.storage_virtualize/actions/workflows/extra-docs-linting.yml, https://github.com/ansible-collections/ibm.storage_virtualize/actions/workflows/galaxy-importer.yml).

**Comment by sumitguptaibm** [comment]
I'll correct the error in runtime.yml day once I am back from vacation.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Felix Fontein ***@***.***>
Sent: Saturday, May 18, 2024 7:43:20 PM
To: ansible-collections/ibm.storage_virtualize ***@***.***>
Cc: Sumit Gupta ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ansible-collections/ibm.storage_virtualize] The collection contains an unmodified docs/docsite/links.yml file (Issue #41)

Please also note that you currently have two of the CI pipelines disabled (https: //github. com/ansible-collections/ibm. storage_virtualize/actions/workflows/extra-docs-linting. yml, https: //github. com/ansible-collections/ibm. storage_virtualize/actions/workflows/galaxy-importer. yml). 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!-HFRWZ5ZeETxVl8SZW8KO7BtXOF_lkyXqjHupRrzLarG5KaMb966vGDgOwWcFsUiCBqSmjHL-zxU9FojapU6HfMn6KlAtKwGLMepTPTMsxmn3hgKS5CBvJKaOOa5C7KHBToLv2BGdw$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Please also note that you currently have two of the CI pipelines disabled (https://github.com/ansible-collections/ibm.storage_virtualize/actions/workflows/extra-docs-linting.yml<https://github.com/ansible-collections/ibm.storage_virtualize/actions/workflows/extra-docs-linting.yml>, https://github.com/ansible-collections/ibm.storage_virtualize/actions/workflows/galaxy-importer.yml<https://github.com/ansible-collections/ibm.storage_virtualize/actions/workflows/galaxy-importer.yml>).

**Comment by sumitguptaibm** [comment]
@felixfontein, I modified the file and requested a review from @Andersson007 (as he was showing up as potential reviewer). 
If it makes sense to make you as reviewer instead, please let me know.

**Comment by sumitguptaibm** [comment]
It was fixed by #42
